services:
  devmate-be:
    build:
      context: devmate/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: devmate1
  postgres:
    image: 'postgres'
    container_name: 'DevMateDB'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

