spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: devmate1
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    use_sql_comments: true
  sql:
    init:
      mode: always
  server:
    port: 8080
devmate:
  prop:
<<<<<<< HEAD
    key: mindyabusiness-devmate-doyathang
    jwtExpiration: 86400000
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
=======
    key: mindyabusiness-devmate-doyathang-mysecretkey-you-wont-know-nothing
    jwtExpiration: 86400000
>>>>>>> add-kotlin-main
