spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/
devmate:
  prop:
    key: mindyabusiness-devmate-doyathang
    jwtExpiration: 86400000

